# The URL the site will be built for
base_url = "http://memoryjoint.com"

theme = "tabi"

title = "Memory Joint"
description = "A place to discuss computing and life."
taxonomies = [{name = "tags", feed = true}]

[markdown]
highlight_code = true
highlight_theme = "css"
