# The URL the site will be built for
base_url = "http://memoryjoint.com"

theme = "tabi"

title = "Memory Joint"
description = "A place to discuss computing and life."
taxonomies = [{name = "tags", feed = true}]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
]
socials = [
    { name = "gitlab", url = "https://gitlab.com/saurabh.2561/", icon = "gitlab" },
    { name = "twitter", url = "https://twitter.com/notintobuying", icon = "twitter" },
]
